###
# block routes
###
kitpages_cms:
    pattern:  /block
    defaults: { _controller: KitpagesCmsBundle:Block:view }

kitpages_cms_block_create:
    pattern:  /block/create
    defaults: { _controller: KitpagesCmsBundle:Block:create }

kitpages_cms_block_edit_success:
    pattern:  /block/edit-success
    defaults: { _controller: KitpagesCmsBundle:Block:editSuccess }

kitpages_cms_block_edit:
    pattern:  /block/edit/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:edit }
    requirements:
        id: \d+

kitpages_cms_block_delete:
    pattern:  /block/delete/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:delete }
    requirements:
        id: \d+

kitpages_cms_block_publish:
    pattern:  /block/publish/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:publish }
    requirements:
        id: \d+

kitpages_cms_block_upload_widget:
    pattern:  /block/uploadWidget/{blockId}/{fieldId}/{parameterList}
    defaults: { _controller: KitpagesCmsBundle:Block:uploadWidget }

kitpages_cms_block_widget:
    pattern:  /block/widget
    defaults: { _controller: KitpagesCmsBundle:Block:widget }

kitpages_cms_zoneblock_delete:
    pattern:  /block/zoneBlockDelete/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:zoneBlockDelete }
    requirements:
        id: \d+


###
# Zones
###
kitpages_cms_zoneblock_moveup:
    pattern:  /zone/moveup/{id}/{block_id}
    defaults: { _controller: KitpagesCmsBundle:Zone:moveUpBlock }
    requirements:
        id: \d+

kitpages_cms_zoneblock_movedown:
    pattern:  /zone/movedown/{id}/{block_id}
    defaults: { _controller: KitpagesCmsBundle:Zone:moveDownBlock }
    requirements:
        id: \d+

kitpages_cms_zone_create:
    pattern:  /zone/create
    defaults: { _controller: KitpagesCmsBundle:Zone:create }

kitpages_cms_zone_publish:
    pattern:  /zone/publish/{id}
    defaults: { _controller: KitpagesCmsBundle:Zone:publish }
    requirements:
        id: \d+

###
# Admin
###
kitpages_cms_admin_view_mode_change:
    pattern:  /admin/viewModeChange/{viewMode}
    defaults: { _controller: KitpagesCmsBundle:Toolbar:viewModeChange }
    requirements:
        id: \d+
kitpages_cms_toolbar_widget_toolbar:
    pattern:  /toolbar/widgetToolbar
    defaults: { _controller: KitpagesCmsBundle:Toolbar:widgetToolbar }

###
# Pages
###

kitpages_cms_page_choice_create:
    pattern:  /page/choiceCreate
    defaults: { _controller: KitpagesCmsBundle:Page:choiceCreate }

kitpages_cms_page_create:
    pattern:  /page/create
    defaults: { _controller: KitpagesCmsBundle:Page:create }

kitpages_cms_page_create_technical:
    pattern:  /page/createTechnical
    defaults: { _controller: KitpagesCmsBundle:Page:createTechnical }

kitpages_cms_page_create_link:
    pattern:  /page/createLink
    defaults: { _controller: KitpagesCmsBundle:Page:createLink }

kitpages_cms_page_edit:
    pattern:  /page/edit/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:edit }
    requirements:
        id: \d+

kitpages_cms_page_edit_technical:
    pattern:  /page/editTechnical/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:editTechnical }
    requirements:
        id: \d+

kitpages_cms_page_edit_link:
    pattern:  /page/editLink/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:editLink }
    requirements:
        id: \d+

kitpages_cms_page_view:
    pattern:  /page/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:view }
    requirements:
        id: \d+


kitpages_cms_page_publish:
    pattern:  /page/publish/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:publish }
    requirements:
        id: \d+

kitpages_cms_createZoneInPage:
    pattern:  /page/createZoneInPage/{id}/{locationInPage}
    defaults: { _controller: KitpagesCmsBundle:Page:createZoneInPage }
    requirements:
        id: \d+
        locationInPage: \w+

kitpages_cms_page_delete:
    pattern:  /page/delete/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:delete }
    requirements:
        id: \d+

kitpages_cms_page_undelete:
    pattern:  /page/undelete/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:undelete }
    requirements:
        id: \d+

kitpages_cms_page_view_lang:
    pattern:  /{lang}/cms/{id}/{urlTitle}
    defaults: { _controller: KitpagesCmsBundle:Page:view, lang: fr }
    requirements:
        id: \d+
        lang:  en|fr
kitpages_cms_page_widget_toolbar:
    pattern:  /page/widgetToolbar/{page}
    defaults: { _controller: KitpagesCmsBundle:Page:widgetToolbar }

kitpages_cms_page_widgetZone:
    pattern:  /page/widgetZone/{location_in_page}/{page}
    defaults: { _controller: KitpagesCmsBundle:Page:widgetZone }

###
# Nav
###
kitpages_cms_nav_publish:
    pattern:  /nav/publish
    defaults: { _controller: KitpagesCmsBundle:Nav:publish }

kitpages_cms_nav_publish_all:
    pattern:  /nav/publishAll
    defaults: { _controller: KitpagesCmsBundle:Nav:publishAll }

kitpages_cms_nav_tree:
    pattern:  /tree
    defaults: { _controller: KitpagesCmsBundle:Nav:tree }

kitpages_cms_nav_moveup:
    pattern:  /nav/moveup/{id}
    defaults: { _controller: KitpagesCmsBundle:Nav:moveUp }
    requirements:
        id: \d+

kitpages_cms_nav_movedown:
    pattern:  /nav/movedown/{id}
    defaults: { _controller: KitpagesCmsBundle:Nav:moveDown }
    requirements:
        id: \d+

kitpages_cms_nav_userpreference_tree:
    pattern:  /nav/userPreference/tree
    defaults: { _controller: KitpagesCmsBundle:Nav:saveUserPreferenceTree }

kitpages_cms_nav_userpreference_tree_scroll:
    pattern:  /nav/userPreference/treeScroll
    defaults: { _controller: KitpagesCmsBundle:Nav:saveUserPreferenceTreeScroll }

kitpages_cms_nav_widgetBreadcrumb:
    pattern:  /nav/widgetBreadcrumb/{slug}/{startDepth}/{page}/{homePageSlug}
    defaults: { _controller: KitpagesCmsBundle:Nav:widgetBreadcrumb }

kitpages_cms_nav_widget:
    pattern:  /nav/widget/{slug}/{startDepth}/{cssClass}/{currentPageSlug}/{endDepth}
    defaults: { _controller: KitpagesCmsBundle:Nav:widget }

###
# Media
###

