<?php

namespace Kitpages\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageZoneRepository extends EntityRepository
{
    public function nbrPageZoneByZoneWithPageDiff($zone, $page)
    {   

        $nbr = $this->_em
            ->createQuery('SELECT count(pz.id) FROM KitpagesCmsBundle:PageZone pz JOIN pz.page p JOIN pz.zone z WHERE pz.page != :page AND pz.zone = :zone')
            ->setParameter("page", $page)
            ->setParameter("zone", $zone)                
            ->getSingleScalarResult();        
        return $nbr;
    }
    
}