<?php
namespace Kitpages\CmsBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Kitpages\CmsBundle\Entity\Site;
/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
   
    public function set($label, $value)
    {

        $dql = "DELETE KitpagesCmsBundle:Site s";
        $dql .= " WHERE s.label = :label";
        $this->_em
                ->createQuery($dql)
                ->setParameter("label", $label)
                ->getResult();
        $site = new Site();
        $site->setLabel($label);
        $site->setValue($value);  
        $this->_em->getConnection()->executeUpdate(
                "INSERT INTO cms_site (label, value) VALUES(?, ?)",
                array($label, $value),
                array(\PDO::PARAM_STR, \PDO::PARAM_STR)
        );
    }    
    
    public function get($label)
    {

        // remove the node from database
        $dql = "SELECT s.value FROM KitpagesCmsBundle:Site s";
        $dql .= " WHERE s.label = :label";
        return $this->_em
                ->createQuery($dql)
                ->setParameter("label", $label)
                ->getSingleScalarResult();

    }
     
}